version: '3.8'

services:
  gunicorn:
    build: ./services/gunicorn
    command: gunicorn --bind 0.0.0.0:5050 wsgi:app 
    volumes:
      - ./services/gunicorn:/code/
    expose:
      - 5050
    env_file:
      - ./.env.dev
    networks: 
      - infovisnet
  nginx:
    build: ./services/nginx
    container_name: nova-proxy
    depends_on:
      - gunicorn
    networks: 
      - infovisnet

networks:
  infovisnet:
    name: infovisnet
